/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.barbeariacortes.view;

import br.com.barbeariacortes.dao.ClienteDAO;
import br.com.barbeariacortes.dto.ClienteDTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TelaInformacoes extends javax.swing.JFrame implements Utilitarios {

    private final TelaInformacoes tl;

    /**
     * Creates new form TelaInformacoes
     */
    public TelaInformacoes() {
        initComponents();
        setSize(700, 600);
        tl = this;
        setTitle("Informações usuário");
        inserirLogo("../src/br/com/barbeariacortes/view/img/icone-info.png", tl);
        setResizable(false); // Define que não pode aumentar o tamanho da tela
        alinharTela(tl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHeading = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        backgroundFormulario = new javax.swing.JPanel();
        jLabelNomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabelHeading.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeading.setText("Informações sobre a Conta");

        btnExcluir.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir Usuário");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        backgroundFormulario.setBackground(new java.awt.Color(153, 153, 153));

        jLabelNomeCompleto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeCompleto.setText("Nome Completo:");

        txtNomeCompleto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCompleto.setText("Matheus Felipe Ruiz Gonçalves");

        jLabelCPF.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF:");

        txtCPF.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(255, 255, 255));
        txtCPF.setText("190.655.994-48");

        jLabelNomeUsuario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setText("Nome de Usuário:");

        txtNomeUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeUsuario.setText("Usuario123");

        jLabelEmail.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("E-mail");

        txtEmail.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("unicv@aluno.unicv.edu.br");

        javax.swing.GroupLayout backgroundFormularioLayout = new javax.swing.GroupLayout(backgroundFormulario);
        backgroundFormulario.setLayout(backgroundFormularioLayout);
        backgroundFormularioLayout.setHorizontalGroup(
            backgroundFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundFormularioLayout.createSequentialGroup()
                .addGroup(backgroundFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeCompleto)
                    .addComponent(jLabelCPF)
                    .addComponent(jLabelNomeUsuario)
                    .addComponent(jLabelEmail)
                    .addGroup(backgroundFormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCompleto)
                            .addComponent(txtCPF)
                            .addComponent(txtNomeUsuario)
                            .addComponent(txtEmail))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        backgroundFormularioLayout.setVerticalGroup(
            backgroundFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCompleto)
                .addGap(13, 13, 13)
                .addComponent(txtNomeCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButton2.setText("Alterar E-mail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnExcluir)
                        .addGap(128, 128, 128)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelHeading)
                        .addComponent(backgroundFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(jButton2))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirUsuario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInformacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundFormulario;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelNomeCompleto;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCPF;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNomeCompleto;
    private javax.swing.JLabel txtNomeUsuario;
    // End of variables declaration//GEN-END:variables

    private void excluirUsuario() {
        String email = txtEmail.getText();
        int excluirusuario = JOptionPane.showConfirmDialog(null, "Deseja excluir o usuário atual(Irreversível)");
        if (excluirusuario == 0) {
            ClienteDTO clienteDTO = new ClienteDTO(email, "");
            ClienteDAO clienteDAO = new ClienteDAO();
            if (!clienteDAO.excluirClienteExistente(clienteDTO)) {

            } else {
                TelaLogin telaLogin = new TelaLogin();
                telaLogin.setVisible(true);
                tl.dispose();
            }
        }

    }

    public JLabel getTxtCPF() {
        return txtCPF;
    }

    public void setTxtCPF(JLabel txtCPF) {
        this.txtCPF = txtCPF;
    }

    public JLabel getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JLabel txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JLabel getTxtNomeCompleto() {
        return txtNomeCompleto;
    }

    public void setTxtNomeCompleto(JLabel txtNomeCompleto) {
        this.txtNomeCompleto = txtNomeCompleto;
    }

    public JLabel getTxtNomeUsuario() {
        return txtNomeUsuario;
    }

    public void setTxtNomeUsuario(JLabel txtNomeUsuario) {
        this.txtNomeUsuario = txtNomeUsuario;
    }

    @Override
    public void inserirLogo(String pathLogo, JFrame tela) {
        tela.setIconImage(Toolkit.getDefaultToolkit().getImage(pathLogo));
    }

    @Override
    public void alinharTela(JFrame jframe) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        jframe.setLocation(x, y);
    }

}
