/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.barbeariacortes.view;

import br.com.barbeariacortes.dao.AgendaDAO;
import br.com.barbeariacortes.dao.ClienteDAO;
import br.com.barbeariacortes.dao.FuncionarioDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TelaPrincipalFunc extends javax.swing.JFrame implements Utilitarios {

    private final TelaPrincipalFunc tl;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalFunc() {
        initComponents();
        setTitle("Principal");
        tl = this;
        inserirLogo("../src/br/com/barbeariacortes/view/img/icone-home.png", tl);
        setSize(700, 700);
        setResizable(false); 
        alinharTela(tl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        jLabelBemVindo = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        background = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        itemUsuario = new javax.swing.JMenu();
        optionInformacoes = new javax.swing.JMenuItem();
        optionCadastroFunc = new javax.swing.JMenuItem();
        itemServico = new javax.swing.JMenu();
        optionServicos = new javax.swing.JMenuItem();
        itemSobreNos = new javax.swing.JMenu();
        optionFaleConosco = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnServicos.setBackground(new java.awt.Color(0, 0, 0));
        btnServicos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnServicos.setText("Serviços");
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));

        jLabelBemVindo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBemVindo.setText("Bem-vindo, ");
        getContentPane().add(jLabelBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtNomeFuncionario.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        txtNomeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeFuncionario.setText("Nome Usuário");
        getContentPane().add(txtNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/background-tela-inicial.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        itemUsuario.setText("Usuário");

        optionInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/icon-info.png"))); // NOI18N
        optionInformacoes.setText("Informações");
        optionInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionInformacoesActionPerformed(evt);
            }
        });
        itemUsuario.add(optionInformacoes);

        optionCadastroFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/icone-funcionario.png"))); // NOI18N
        optionCadastroFunc.setText("Cadastrar Funcionário");
        optionCadastroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCadastroFuncActionPerformed(evt);
            }
        });
        itemUsuario.add(optionCadastroFunc);

        jMenuBar.add(itemUsuario);

        itemServico.setText("Serviços");

        optionServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/icone-tesoura.png"))); // NOI18N
        optionServicos.setText("Serviços");
        optionServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionServicosActionPerformed(evt);
            }
        });
        itemServico.add(optionServicos);

        jMenuBar.add(itemServico);

        itemSobreNos.setText("Informações");
        itemSobreNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreNosActionPerformed(evt);
            }
        });

        optionFaleConosco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/icon-telefone.png"))); // NOI18N
        optionFaleConosco.setText("Fale conosco");
        optionFaleConosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionFaleConoscoActionPerformed(evt);
            }
        });
        itemSobreNos.add(optionFaleConosco);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/icon-pessoa-corte.png"))); // NOI18N
        jMenuItem1.setText("Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemSobreNos.add(jMenuItem1);

        jMenuBar.add(itemSobreNos);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSobreNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreNosActionPerformed

    }//GEN-LAST:event_itemSobreNosActionPerformed

    private void optionFaleConoscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionFaleConoscoActionPerformed
        TelaContato telaContato = new TelaContato();
        telaContato.setVisible(true);
    }//GEN-LAST:event_optionFaleConoscoActionPerformed

    private void optionInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionInformacoesActionPerformed

        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

        if (funcionarioDAO.eFuncionario(txtNomeFuncionario.getText())) {
            TelaInformacoesF telaInformacoesF = new TelaInformacoesF();
            telaInformacoesF.setVisible(true);
            telaInformacoesF.getTxtNomeCompleto().setText(txtNomeFuncionario.getText());
            telaInformacoesF.getTxtCPF().setText(funcionarioDAO.getCPF(txtNomeFuncionario.getText()));
            telaInformacoesF.getTxtSalario().setText(funcionarioDAO.getSalario(txtNomeFuncionario.getText()));
            telaInformacoesF.getTxtEmail().setText(funcionarioDAO.getEmail(txtNomeFuncionario.getText()));
        }
    }//GEN-LAST:event_optionInformacoesActionPerformed

    private void optionServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionServicosActionPerformed
        TelaServicosF telaServicosF = new TelaServicosF();
        telaServicosF.setVisible(true);
    }//GEN-LAST:event_optionServicosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaFuncionarios telaFuncionario = new TelaFuncionarios();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        TelaServicosF telaServicos = new TelaServicosF();
        telaServicos.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        voltarTelaLogin();
    }//GEN-LAST:event_btnSairActionPerformed

    private void optionCadastroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCadastroFuncActionPerformed
        TelaCadastroFunc tela = new TelaCadastroFunc();
        tela.setVisible(true);
    }//GEN-LAST:event_optionCadastroFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnServicos;
    private javax.swing.JMenu itemServico;
    private javax.swing.JMenu itemSobreNos;
    private javax.swing.JMenu itemUsuario;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem optionCadastroFunc;
    private javax.swing.JMenuItem optionFaleConosco;
    private javax.swing.JMenuItem optionInformacoes;
    private javax.swing.JMenuItem optionServicos;
    private javax.swing.JLabel txtNomeFuncionario;
    // End of variables declaration//GEN-END:variables

    private void voltarTelaLogin() {
        int result = JOptionPane.showConfirmDialog(null, "Deseja Sair para a tela inicial?");
        if (result == 0) {
            TelaLogin telaLogin = new TelaLogin();
            telaLogin.setVisible(true);
            tl.dispose();
        }
    }

    public JLabel getTxtNomeUsuario() {
        return txtNomeFuncionario;
    }

    public void setTxtNomeUsuario(JLabel txtNomeUsuario) {
        this.txtNomeFuncionario = txtNomeUsuario;
    }

    @Override
    public void inserirLogo(String pathLogo, JFrame tela) {
        tela.setIconImage(Toolkit.getDefaultToolkit().getImage(pathLogo));
    }

    @Override
    public void alinharTela(JFrame jframe) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        jframe.setLocation(x, y);
    }

}
