/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.barbeariacortes.view;

import br.com.barbeariacortes.dao.AgendaDAO;
import br.com.barbeariacortes.dao.ClienteDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class TelaAgendamento extends javax.swing.JFrame implements Utilitarios {

    private final TelaAgendamento tl;

    /**
     * Creates new form TelaAgendamento
     */
    public TelaAgendamento() {
        initComponents();
        setSize(700, 600);
        setTitle("Agendamentos");

        setResizable(false); // Define que não pode aumentar o tamanho da tela
        tl = this;

        inserirLogo("../src/br/com/barbeariacortes/view/img/icon-calendario.png", tl);
        alinharTela(tl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        tableAgendamentos = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        btnAgendar = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        jLabelIdCliente = new javax.swing.JLabel();
        btnExcluirAgendamento = new javax.swing.JButton();
        jLabelExclusaoAgendamento = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setPreferredSize(new java.awt.Dimension(700, 500));

        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Hora", "Nome Funcionario", "Serviço", "Preço"
            }
        ));
        tblAgendamentos.setEnabled(false);
        tableAgendamentos.setViewportView(tblAgendamentos);
        if (tblAgendamentos.getColumnModel().getColumnCount() > 0) {
            tblAgendamentos.getColumnModel().getColumn(0).setMinWidth(100);
            tblAgendamentos.getColumnModel().getColumn(0).setMaxWidth(100);
            tblAgendamentos.getColumnModel().getColumn(1).setMinWidth(100);
            tblAgendamentos.getColumnModel().getColumn(1).setMaxWidth(100);
            tblAgendamentos.getColumnModel().getColumn(2).setMinWidth(200);
            tblAgendamentos.getColumnModel().getColumn(2).setMaxWidth(200);
            tblAgendamentos.getColumnModel().getColumn(3).setMinWidth(180);
            tblAgendamentos.getColumnModel().getColumn(3).setMaxWidth(180);
            tblAgendamentos.getColumnModel().getColumn(4).setMinWidth(130);
            tblAgendamentos.getColumnModel().getColumn(4).setMaxWidth(130);
        }

        btnAgendar.setBackground(new java.awt.Color(0, 255, 0));
        btnAgendar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendar.setText("Agendar");
        btnAgendar.setBorderPainted(false);
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Agendamentos");

        btnExcluirAgendamento.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirAgendamento.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnExcluirAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirAgendamento.setText("Excluir Agendamento");
        btnExcluirAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAgendamentoActionPerformed(evt);
            }
        });

        jLabelExclusaoAgendamento.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelExclusaoAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExclusaoAgendamento.setText("Exclusão de Agendamento");

        jLabelData.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora");

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(heading))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabelIdCliente)
                                .addGap(200, 200, 200)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHora, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(txtData))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tableAgendamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelExclusaoAgendamento)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabelData)))
                .addGap(207, 207, 207))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(btnAgendar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnExcluirAgendamento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExclusaoAgendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdCliente))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirAgendamento)
                .addGap(52, 52, 52))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        TelaCadastroAgendamento tela = new TelaCadastroAgendamento();
        tela.setVisible(true);
        this.dispose();
        tela.getjLabelIdCliente().setText(this.getjLabelIdCliente().getText());
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnExcluirAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAgendamentoActionPerformed
        excluirRegistro();
    }//GEN-LAST:event_btnExcluirAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnExcluirAgendamento;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelExclusaoAgendamento;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JScrollPane tableAgendamentos;
    private javax.swing.JTable tblAgendamentos;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtHora;
    // End of variables declaration//GEN-END:variables

    private void excluirRegistro() {
        String[] partesData = txtData.getText().replaceAll("/", "-").split("-");
        String data = partesData[2] + "-" + partesData[1] + "-" + partesData[0];

        String hora = txtHora.getText() + ":00";
        AgendaDAO agendaDAO = new AgendaDAO();
        ClienteDAO clienteDAO = new ClienteDAO();
        if (agendaDAO.excluirAgendamento(data, hora, Integer.parseInt(jLabelIdCliente.getText()))) {
            JOptionPane.showMessageDialog(null, "Excluído agendamento com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Erro, não existe esse agendamento");
        }
        agendaDAO.preencherTabelaAgendamentos(Integer.parseInt(jLabelIdCliente.getText()), this);
    }

    public JTable getTblAgendamentos() {
        return tblAgendamentos;
    }

    public void setTblAgendamentos(JTable tblAgendamentos) {
        this.tblAgendamentos = tblAgendamentos;
    }

    public JLabel getjLabelIdCliente() {
        return jLabelIdCliente;
    }

    public void setjLabelIdCliente(JLabel jLabelIdCliente) {
        this.jLabelIdCliente = jLabelIdCliente;
    }

    @Override
    public void inserirLogo(String pathLogo, JFrame tela) {
        tela.setIconImage(Toolkit.getDefaultToolkit().getImage(pathLogo));
    }

    @Override
    public void alinharTela(JFrame jframe) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        jframe.setLocation(x, y);
    }
}
