/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.barbeariacortes.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class TelaContato extends javax.swing.JFrame implements Utilitarios{

    /**
     * Creates new form TelaContato
     */
    public TelaContato() {
        initComponents();
        TelaContato tl = this;
        setTitle("Contato");
        inserirLogo("../src/br/com/barbeariacortes/view/img/icone-contato.png", tl);
        setSize(700, 700);
        setResizable(false); // Define que não pode aumentar o tamanho da tela
        alinharTela(tl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        iconFacebook = new javax.swing.JLabel();
        jLabelFacebook = new javax.swing.JLabel();
        jLabelWhatsapp = new javax.swing.JLabel();
        iconWhatsapp = new javax.swing.JLabel();
        jLabelLinkedin = new javax.swing.JLabel();
        iconLinkedin = new javax.swing.JLabel();
        iconMapa = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        iconTelefone = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0));

        iconFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/facebook.png"))); // NOI18N

        jLabelFacebook.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelFacebook.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFacebook.setText("AdemirCortes");

        jLabelWhatsapp.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelWhatsapp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWhatsapp.setText("(44) 99780-3020");

        iconWhatsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/whatsapp.png"))); // NOI18N

        jLabelLinkedin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelLinkedin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLinkedin.setText("@AdemirCortes");

        iconLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/linkedin.png"))); // NOI18N

        iconMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/googleMap.jpeg"))); // NOI18N

        jLabelEndereco.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereco.setText("Av. Advogado Horácio Raccanello Filho - Novo Centro, Maringá - PR, 87020-035");

        iconTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/telefone.png"))); // NOI18N

        jLabelTelefone.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText(" (44) 3028-4416");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(iconFacebook)
                        .addGap(185, 185, 185)
                        .addComponent(iconWhatsapp)
                        .addGap(216, 216, 216)
                        .addComponent(iconLinkedin))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFacebook)
                        .addGap(83, 83, 83)
                        .addComponent(jLabelWhatsapp)
                        .addGap(91, 91, 91)
                        .addComponent(jLabelLinkedin))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(iconMapa))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelEndereco))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(iconTelefone)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTelefone)))
                .addContainerGap(922, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(iconFacebook))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(iconLinkedin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconWhatsapp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFacebook)
                    .addComponent(jLabelWhatsapp)
                    .addComponent(jLabelLinkedin))
                .addGap(110, 110, 110)
                .addComponent(iconMapa)
                .addGap(18, 18, 18)
                .addComponent(jLabelEndereco)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabelTelefone))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(iconTelefone)))
                .addContainerGap(556, Short.MAX_VALUE))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel iconFacebook;
    private javax.swing.JLabel iconLinkedin;
    private javax.swing.JLabel iconMapa;
    private javax.swing.JLabel iconTelefone;
    private javax.swing.JLabel iconWhatsapp;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFacebook;
    private javax.swing.JLabel jLabelLinkedin;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelWhatsapp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inserirLogo(String pathLogo, JFrame tela) {
        tela.setIconImage(Toolkit.getDefaultToolkit().getImage(pathLogo));
    }

    @Override
    public void alinharTela(JFrame jframe) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

        jframe.setLocation(x, y);
    }
}
