package br.com.barbeariacortes.view;

import br.com.barbeariacortes.dao.ClienteDAO;
import br.com.barbeariacortes.dao.FuncionarioDAO;
import br.com.barbeariacortes.dto.ClienteDTO;
import br.com.barbeariacortes.dto.FuncionarioDTO;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class TelaLogin extends javax.swing.JFrame implements Utilitarios {

    private final TelaLogin tl;

    public TelaLogin() {
        initComponents();
        setTitle("Logar");
        setSize(700, 500);
        setResizable(false); // Define que não pode aumentar o tamanho da tela
        tl = this;
        inserirLogo("../src/br/com/barbeariacortes/view/img/icone-login.png", tl);
        alinharTela(tl);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JButton();
        btnEsqueceuSenha = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmail.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("E-mail");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 370, 30));

        jLabelSenha.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 360, 30));

        btnLogar.setBackground(new java.awt.Color(0, 0, 0));
        btnLogar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnLogar.setForeground(new java.awt.Color(255, 255, 255));
        btnLogar.setText("Logar");
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        btnEsqueceuSenha.setBackground(new java.awt.Color(153, 153, 153));
        btnEsqueceuSenha.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEsqueceuSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnEsqueceuSenha.setText("Esqueceu a senha");
        btnEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsqueceuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        btnCadastrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCadastrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/barbeariacortes/view/img/background-tela-login.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        try {
            String email = txtEmail.getText().toLowerCase();
            String senha = txtPassword.getText();

            FuncionarioDTO funcionarioDTO = new FuncionarioDTO(email, senha);
            ClienteDTO clienteDTO = new ClienteDTO(email, senha);

            ClienteDAO clienteDAO = new ClienteDAO();
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

            boolean resultado = clienteDAO.autentifacaoCliente(clienteDTO);
            boolean resultadoF = funcionarioDAO.autentifacaoFuncioario(funcionarioDTO);

            if (resultadoF) {
                TelaPrincipalFunc telaPrincipal = new TelaPrincipalFunc();
                telaPrincipal.setVisible(true);
                telaPrincipal.getTxtNomeUsuario().setText(funcionarioDAO.getNomeCompleto(email));
                tl.dispose();

            } else if (resultado) {
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                telaPrincipal.getTxtNomeUsuario().setText(clienteDAO.getNomeUsuario(email));
                tl.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "E-mail ou senha errado, por favor digite novamente");
            }

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro: " + exception);

        }
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
        tl.dispose();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuSenhaActionPerformed
        TelaEsqueceuSenha tela = new TelaEsqueceuSenha();
        tela.setVisible(true);
        tl.dispose();
    }//GEN-LAST:event_btnEsqueceuSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsqueceuSenha;
    private javax.swing.JButton btnLogar;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void inserirLogo(String pathLogo, JFrame tela) {
        tela.setIconImage(Toolkit.getDefaultToolkit().getImage(pathLogo));
    }

    @Override
    public void alinharTela(JFrame jframe) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Calcula as coordenadas X e Y para posicionar o JFrame no centro
        int frameWidth = jframe.getWidth();
        int frameHeight = jframe.getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;

       jframe.setLocation(x, y);
    }

}
